:name: star-wars
:long-name: Star Wars
:description: Exploring a Star Wars Dataset in Neo4j
:icon: documentation/img/star-wars-logo.svg
:tags: example-data, dataset, star-wars, movies, science-fiction
:author: Jonathan Thein
:demodb: false
:data: import/*.csv
:use-load-script: false
:use-dump-file: false
:zip-file: trues
:use-plugin: false
:target-db-version: 4.4
:bloom-perspective: bloom/star-wars.bloom-perspective
:guide: documentation/star-wars.neo4j-browser-guide
:rendered-guide: https://guides.neo4j.com/{name}/index.html
:model: documentation/img/model.svg
:example: documentation/img/example.svg

:todo: false
image::{icon}[width=100]

== {long-name} Graph Example

Description: _{description}_

Source: https://www.kaggle.com/datasets/jsphyg/star-wars
Video: https://www.youtube.com/watch?v=fdPWH4P4V5A

ifeval::[{todo} != false]
To Do: {todo}
endif::[]

.Model
image::{model}[]

.Example
image::{example}[width=600]

.Example Query:
[source,cypher,role=query-example,param-name=species,param-value="Human",result-column=planet,expected-result=Tatooine]
----
MATCH (s:Species)<-[:IDENTIFIES_AS]-(c:Character)-[:FROM]->(p:Planet)
WHERE s.name = $species
 RETURN DISTINCT p.name as planet
----

=== Setup

This is for Neo4j version: {target-db-version}

ifeval::[{use-plugin} != false]
Required plugins: {use-plugin}
endif::[]

ifeval::[{demodb} != false]
The database is also available on https://demo.neo4jlabs.com:7473

Username "{name}", password: "{name}", database: "{name}"
endif::[]

Rendered guide available via: `:play {rendered-guide}`

Unrendered guide: link:{guide}[]

Load graph data via the following:

ifeval::[{data} != false]
==== Data files: `{data}`

Import flat files (csv, json, etc) using Cypher's https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`], https://neo4j.com/labs/apoc/[APOC library], or https://neo4j.com/developer/data-import/[other methods].
endif::[]

ifeval::[{use-dump-file} != false]
==== Dump file: `{use-dump-file}`

* Drop the file into the `Files` section of a project in Neo4j Desktop. Then choose the option to `Create new DBMS from dump` option from the file options.

* Use the neo4j-admin tool to load data from the command line with the command below.

[source,shell,subs=attributes]
----
bin/neo4j-admin load --from {use-dump-file} [--database "database"]
----

* Upload the dump file to Neo4j Aura via https://console.neo4j.io/#import-instructions
endif::[]

ifeval::[{use-load-script} != false]
==== Data load script: `{use-load-script}`

[source,shell,subs=attributes]
----
bin/cypher-shell -u neo4j -p "password" -f {use-load-script} [-d "database"]
----

Or import in Neo4j Browser by dragging or pasting the content of {use-load-script}.
endif::[]

ifeval::[{zip-file} != false]
==== Zipe file

Download the zip file link:{repo}/raw/master/{name}.zip[{name}.zip] and add it as "project from file" to https://neo4j.com/developer/neo4j-desktop[Neo4j Desktop^].
endif::[]

=== Code Examples

* link:code/javascript/example.js[JavaScript]
* link:code/java/Example.java[Java]
* link:code/csharp/Example.cs[C#]
* link:code/python/example.py[Python]
* link:code/go/example.go[Go]

=== Feedback

Feel free to submit issues or pull requests for improvement on this repository.